spring:
  application:
    name: message-poller

  datasource:
    message:
      order:
        jdbc-url: test_1
        username: test_1
        password: test_1
        driver-class-name: test_1
      payment:
        jdbc-url: test_1
        username: test_1
        password: test_1
        driver-class-name: test_1

  hibernate:
    dialect:
      order: test_1
      payment: test_1

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

outbox:
  topic:
    order: test_1
    payment: test_2
